spring.application.name=lab05

server.port=8081
spring.datasource.url=jdbc:hsqldb:hsql://localhost/workdb

# Drop and Create table at startup, good for learning/testing
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
